# Use root/example as user/password credentials
version: '3.1'
services:
  selenium-test-soat:
    image: selenium-test-soat
    build: 
      context: ./
    container_name: selenium-test-soat
    volumes:
      - /home/sinergia/Escritorio/testeo:/testeo