version: 2
jobs:
  test-python-3.7: &template
    docker:
      - image: circleci/python:3.7
      - image: PruebaR5/docker-compose.yml

    working_directory: ~/PruebaR5

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: prueba
          command: echo "Hola mundo"
      - run:
          name: run tests
          command: sh run_tests.sh

  test-python-3.6:
    <<: *template
    docker:
      - image: circleci/python:3.6

  test-python-3.8:
    <<: *template
    docker:
      - image: circleci/python:3.8

  test-python-3.9:
    <<: *template
    docker:
      - image: circleci/python:3.9


workflows:
  version: 2
  test:
    jobs:
      - test-python-3.7
      - test-python-3.8
      - test-python-3.9